tasks:
  - name: Install
    init: >
      npm install &&
      gp sync-done install
  - name: Run Webpack
    init: gp sync-await install
    command: npm start
  - name: Editor server
    init: gp sync-await install # wait for the above 'install' to finish
    command: npm run editor-remote
ports:
  - port: 1959
    onOpen: open-preview